[versions]
picocli = "4.7.7"
junit-bom = "5.12.2"
versions-plugin = "0.52.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter"}
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }
